const categories = [
  {
    slug: "technology",
    name: "Technology",
    emoji: "💻",
    description: "Development, IT, data and everything code.",
    openRequests: 324,
  },
  {
    slug: "design",
    name: "Design",
    emoji: "🎨",
    description: "Logos, branding, UI/UX and illustration.",
    openRequests: 184,
  },
  {
    slug: "education",
    name: "Education",
    emoji: "📚",
    description: "Tutoring, courses and exam preparation.",
    openRequests: 231,
  },
  {
    slug: "student-pfe",
    name: "Student & PFE",
    emoji: "🎓",
    description: "Internships, teammates and graduation projects.",
    openRequests: 412,
  },
  {
    slug: "freelance",
    name: "Freelance",
    emoji: "💼",
    description: "Short missions for independent professionals.",
    openRequests: 268,
  },
  {
    slug: "services",
    name: "Services",
    emoji: "🔧",
    description: "Repairs, installation and everyday help.",
    openRequests: 157,
  },
  {
    slug: "photography",
    name: "Photography",
    emoji: "📸",
    description: "Events, portraits, product shoots.",
    openRequests: 96,
  },
  {
    slug: "writing",
    name: "Writing & Translation",
    emoji: "📝",
    description: "Content, CVs, translation and proofreading.",
    openRequests: 121,
  },
  {
    slug: "transport",
    name: "Transport",
    emoji: "🚗",
    description: "Moving, delivery and shared rides.",
    openRequests: 74,
  },
  {
    slug: "home",
    name: "Home",
    emoji: "🏠",
    description: "Cleaning, furniture, renovation and DIY.",
    openRequests: 88,
  },
  {
    slug: "buy-sell",
    name: "Buying & Selling",
    emoji: "🛍️",
    description: "Find, resell or source what you need.",
    openRequests: 143,
  },
  {
    slug: "recommendations",
    name: "Recommendations",
    emoji: "💡",
    description: "Ask the community who they trust.",
    openRequests: 205,
  },
];
function categoryBySlug(slug) {
  return categories.find((c) => c.slug === slug) ?? categories[0];
}
const mkUser = (u2) => ({
  initials: u2.name
    .split(" ")
    .map((p) => p[0])
    .slice(0, 2)
    .join(""),
  headline: "Talab member",
  location: "Tunis",
  rating: 4.7,
  completed: 12,
  offersAccepted: 9,
  responseRate: 94,
  avgResponse: "3h",
  skills: [],
  about: "",
  ...u2,
});
const defaultPrivacy = {
  profilePublic: true,
  showEmail: false,
  showPhone: false,
  showResume: true,
};
const currentUser = mkUser({
  id: "u1",
  name: "Sarah Ben Ali",
  username: "sarahba",
  email: "sarah.benali@talab.tn",
  phone: "+216 22 145 987",
  headline: "Software Engineering Student",
  location: "Tunis",
  rating: 4.8,
  completed: 18,
  offersAccepted: 23,
  responseRate: 96,
  avgResponse: "2h",
  skills: ["React", "Node.js", "UI/UX"],
  about:
    "Final-year software engineering student in Tunis. I build web apps, help with front-end projects and I'm always happy to give a hand on student projects.",
  resume: { name: "sarah-ben-ali-cv.pdf", size: "412 KB", uploadedAt: "Aug 12, 2026" },
  privacy: defaultPrivacy,
  education: [
    {
      id: "e1",
      school: "INSAT — Tunis",
      degree: "Engineering degree, Software Engineering",
      period: "2021 — 2026",
    },
    {
      id: "e2",
      school: "Lycée Pilote Ariana",
      degree: "Baccalauréat, Mathematics",
      period: "2018 — 2021",
    },
  ],
  experience: [
    {
      id: "x1",
      company: "Freelance",
      role: "Front-end developer",
      period: "2024 — now",
      summary: "React and Tailwind interfaces for small Tunisian businesses and student startups.",
    },
    {
      id: "x2",
      company: "Vermeg",
      role: "Software engineering intern",
      period: "Summer 2025",
      summary: "Built internal dashboards and improved test coverage on a fintech product.",
    },
  ],
  reviews: [
    {
      id: "rv1",
      author: "Ahmed Trabelsi",
      authorInitials: "AT",
      rating: 5,
      body: "Clear brief, fast answers and paid on time. A pleasure to work with.",
      requestTitle: "Logo for my startup",
      createdAt: "2 weeks ago",
    },
    {
      id: "rv2",
      author: "Ines Gharbi",
      authorInitials: "IG",
      rating: 5,
      body: "Sarah helped me fix my React project in one evening. Highly recommended.",
      requestTitle: "Help with a React bug",
      createdAt: "1 month ago",
    },
    {
      id: "rv3",
      author: "Mohamed Khelifi",
      authorInitials: "MK",
      rating: 4,
      body: "Good collaboration, delivery was slightly late but the quality was there.",
      requestTitle: "Landing page integration",
      createdAt: "2 months ago",
    },
  ],
});
const users = [
  currentUser,
  mkUser({
    id: "u2",
    name: "Ahmed Trabelsi",
    headline: "Brand & Logo Designer",
    rating: 4.9,
    completed: 24,
    skills: ["Illustrator", "Branding", "Figma"],
    about: "Freelance designer, 6 years of branding work for Tunisian startups.",
    online: true,
  }),
  mkUser({
    id: "u3",
    name: "Mohamed Khelifi",
    headline: "Full-stack Developer",
    location: "Sousse",
    rating: 4.6,
    completed: 31,
    skills: ["React", "Laravel", "PostgreSQL"],
  }),
  mkUser({
    id: "u4",
    name: "Ines Gharbi",
    headline: "English Teacher & Translator",
    location: "Ariana",
    rating: 5,
    completed: 41,
    skills: ["English", "Translation", "IELTS"],
    online: true,
  }),
  mkUser({
    id: "u5",
    name: "Yassine Mabrouk",
    headline: "Event Photographer",
    location: "Sfax",
    rating: 4.7,
    completed: 17,
    skills: ["Photography", "Lightroom", "Video"],
  }),
];
const u = (id) => users.find((x) => x.id === id) ?? currentUser;
const requests = [
  {
    id: "r1",
    title: "I need a logo for my startup",
    description:
      "I'm looking for a designer to create a simple modern logo for a new project in the food delivery space. I already have a name and a rough idea of the colors (green + white). I'd like 2 or 3 concepts, then one round of revisions on the chosen direction. Source files required (AI or Figma) plus PNG/SVG exports.",
    category: "design",
    author: u("u1"),
    createdAt: "2h ago",
    budgetMin: 100,
    budgetMax: 200,
    location: "Tunis",
    remote: true,
    urgency: "normal",
    deadline: "Sep 5",
    status: "open",
    commentsCount: 12,
    offersCount: 4,
    skills: ["Logo design", "Branding", "Figma"],
    offers: [
      {
        id: "o1",
        user: u("u2"),
        message:
          "I can create the logo in 3 days, with 3 concepts and one revision round. Source files included.",
        price: 150,
        days: 3,
        status: "pending",
        requestId: "r1",
        requestTitle: "I need a logo for my startup",
        createdAt: "1h ago",
        portfolio: "https://behance.net/ahmed",
      },
      {
        id: "o2",
        user: u("u5"),
        message: "Happy to help — I do branding on the side and can deliver this week.",
        price: 120,
        days: 5,
        status: "pending",
        requestId: "r1",
        requestTitle: "I need a logo for my startup",
        createdAt: "40m ago",
      },
    ],
    comments: [
      {
        id: "c1",
        user: u("u3"),
        body: "I know a designer who might be interested. I'll send you his contact.",
        createdAt: "2 hours ago",
        likes: 4,
        replies: [
          {
            id: "c1r1",
            user: u("u1"),
            body: "That would be great, thank you Mohamed!",
            createdAt: "1 hour ago",
            likes: 1,
          },
        ],
      },
      {
        id: "c2",
        user: u("u4"),
        body: "Do you need the logo in Arabic too? That usually changes the price a bit.",
        createdAt: "1 hour ago",
        likes: 2,
      },
    ],
  },
  {
    id: "r2",
    title: "Need a React developer for a small project",
    description:
      "Small dashboard with 4 screens, the design is already done in Figma. Looking for someone who can integrate it cleanly with React + Tailwind.",
    category: "technology",
    author: u("u3"),
    createdAt: "5h ago",
    budgetMin: 400,
    budgetMax: 800,
    location: "Remote",
    remote: true,
    urgency: "urgent",
    deadline: "Sep 12",
    status: "open",
    commentsCount: 6,
    offersCount: 9,
    skills: ["React", "Tailwind", "TypeScript"],
    offers: [],
    comments: [],
  },
  {
    id: "r3",
    title: "Looking for a teammate for my PFE",
    description:
      "Final year project about a smart irrigation system. Looking for someone into embedded systems or mobile development to team up with.",
    category: "student-pfe",
    author: u("u4"),
    createdAt: "1d ago",
    budgetMin: 0,
    budgetMax: 0,
    location: "Ariana",
    remote: false,
    urgency: "normal",
    deadline: "Oct 1",
    status: "in_progress",
    commentsCount: 21,
    offersCount: 3,
    skills: ["IoT", "Flutter", "Arduino"],
    offers: [],
    comments: [],
  },
  {
    id: "r4",
    title: "Does anyone know a good English teacher?",
    description:
      "Looking for a recommendation for a serious English teacher for conversation practice, twice a week, around Lac 2.",
    category: "recommendations",
    author: u("u2"),
    createdAt: "1d ago",
    budgetMin: 30,
    budgetMax: 60,
    location: "Tunis",
    remote: false,
    urgency: "low",
    deadline: "Sep 20",
    status: "open",
    commentsCount: 34,
    offersCount: 7,
    skills: ["English", "Tutoring"],
    offers: [],
    comments: [],
  },
  {
    id: "r5",
    title: "Need someone to repair my laptop",
    description:
      "Lenovo ThinkPad, doesn't charge anymore. I think it's the charging port. Somewhere in Sfax if possible.",
    category: "services",
    author: u("u5"),
    createdAt: "2d ago",
    budgetMin: 50,
    budgetMax: 120,
    location: "Sfax",
    remote: false,
    urgency: "urgent",
    deadline: "Sep 2",
    status: "completed",
    commentsCount: 4,
    offersCount: 5,
    skills: ["Hardware", "Repair"],
    offers: [],
    comments: [],
  },
  {
    id: "r6",
    title: "Looking for someone to edit a 5-minute video",
    description:
      "Short documentary about a student association. Raw footage is ready (about 40 min), I need cutting, color and subtitles.",
    category: "photography",
    author: u("u1"),
    createdAt: "3d ago",
    budgetMin: 200,
    budgetMax: 350,
    location: "Remote",
    remote: true,
    urgency: "normal",
    deadline: "Sep 18",
    status: "open",
    commentsCount: 9,
    offersCount: 6,
    skills: ["Premiere Pro", "Subtitles", "Color"],
    offers: [],
    comments: [],
  },
];
function requestById(id) {
  return requests.find((r) => r.id === id);
}
const myOffers = [
  {
    id: "mo1",
    user: currentUser,
    message: "I can build the dashboard integration in a week.",
    price: 150,
    days: 3,
    status: "pending",
    requestId: "r1",
    requestTitle: "Logo Design",
    createdAt: "1h ago",
  },
  {
    id: "mo2",
    user: currentUser,
    message: "Available to start immediately, React + Tailwind is my daily stack.",
    price: 600,
    days: 10,
    status: "accepted",
    requestId: "r2",
    requestTitle: "React developer for a small project",
    createdAt: "2d ago",
  },
  {
    id: "mo3",
    user: currentUser,
    message: "I can help with subtitles and color grading.",
    price: 250,
    days: 6,
    status: "rejected",
    requestId: "r6",
    requestTitle: "Video editing — 5 minutes",
    createdAt: "4d ago",
  },
  {
    id: "mo4",
    user: currentUser,
    message: "Repaired the charging port and cleaned the fans.",
    price: 90,
    days: 2,
    status: "completed",
    requestId: "r5",
    requestTitle: "Laptop repair",
    createdAt: "1w ago",
  },
];
const notifications = [
  {
    id: "n1",
    icon: "💬",
    text: "Sarah commented on your request “Logo for my startup”.",
    time: "5m ago",
    read: false,
    href: "/request/r1",
  },
  {
    id: "n2",
    icon: "💰",
    text: "Ahmed made an offer of 150 TND on your request.",
    time: "1h ago",
    read: false,
    href: "/request/r1",
  },
  {
    id: "n3",
    icon: "🎉",
    text: "Your offer was accepted on “React developer for a small project”.",
    time: "3h ago",
    read: false,
    href: "/my-offers",
  },
  {
    id: "n4",
    icon: "↩️",
    text: "Mohamed replied to your comment.",
    time: "1d ago",
    read: true,
    href: "/request/r1",
  },
  {
    id: "n5",
    icon: "⭐",
    text: "You received a 5-star review from Ines Gharbi.",
    time: "2d ago",
    read: true,
    href: "/profile",
  },
];
const conversations = [
  {
    id: "cv1",
    user: u("u2"),
    lastMessage: "Hi, I can help with your React project.",
    time: "2m",
    unread: 2,
    messages: [
      { id: "m1", fromMe: false, body: "Hi Sarah! I saw your request for a logo.", time: "10:02" },
      { id: "m2", fromMe: true, body: "Hi Ahmed, thanks for reaching out 🙌", time: "10:05" },
      {
        id: "m3",
        fromMe: false,
        body: "I can send you 3 concepts by Friday. Would that work?",
        time: "10:06",
      },
      {
        id: "m4",
        fromMe: true,
        body: "Perfect. Can you also share a couple of past logos?",
        time: "10:09",
        read: true,
      },
      { id: "m5", fromMe: false, body: "Sure, sending my portfolio now.", time: "10:11" },
    ],
  },
  {
    id: "cv2",
    user: u("u3"),
    lastMessage: "The dashboard repo is ready when you are.",
    time: "1h",
    unread: 0,
    messages: [
      { id: "m1", fromMe: false, body: "The dashboard repo is ready when you are.", time: "09:14" },
      {
        id: "m2",
        fromMe: true,
        body: "Great, I'll start tomorrow morning.",
        time: "09:20",
        read: true,
      },
    ],
  },
  {
    id: "cv3",
    user: u("u4"),
    lastMessage: "Thank you for the recommendation!",
    time: "1d",
    unread: 0,
    messages: [
      { id: "m1", fromMe: false, body: "Thank you for the recommendation!", time: "Yesterday" },
    ],
  },
];
const locations = [
  "Tunis",
  "Ariana",
  "Ben Arous",
  "Manouba",
  "Nabeul",
  "Bizerte",
  "Sousse",
  "Monastir",
  "Sfax",
  "Gabès",
  "Kairouan",
  "Remote",
];
const statusMeta = {
  open: { label: "Open", dot: "🟢", className: "bg-success-soft text-success" },
  in_progress: {
    label: "In progress",
    dot: "🟡",
    className: "bg-warning-soft text-warning-foreground",
  },
  completed: { label: "Completed", dot: "🔵", className: "bg-info-soft text-info" },
  cancelled: { label: "Cancelled", dot: "🔴", className: "bg-destructive/10 text-destructive" },
};
const offerStatusMeta = {
  pending: { label: "Pending", className: "bg-warning-soft text-warning-foreground" },
  accepted: { label: "Accepted", className: "bg-success-soft text-success" },
  rejected: { label: "Rejected", className: "bg-destructive/10 text-destructive" },
  completed: { label: "Completed", className: "bg-info-soft text-info" },
};
function userById(id) {
  return users.find((u2) => u2.id === id);
}
const genericEducation = [
  { id: "ge1", school: "Université de Tunis", degree: "Licence", period: "2018 — 2021" },
];
const genericReviews = [
  {
    id: "grv1",
    author: "Sarah Ben Ali",
    authorInitials: "SB",
    rating: 5,
    body: "Delivered exactly what was agreed, on time. Would work with again.",
    requestTitle: "Logo for my startup",
    createdAt: "3 weeks ago",
  },
  {
    id: "grv2",
    author: "Yassine Mabrouk",
    authorInitials: "YM",
    rating: 5,
    body: "Very responsive and easy to communicate with.",
    requestTitle: "Event photography",
    createdAt: "2 months ago",
  },
];
export {
  categories,
  categoryBySlug,
  conversations,
  currentUser,
  defaultPrivacy,
  genericEducation,
  genericReviews,
  locations,
  myOffers,
  notifications,
  offerStatusMeta,
  requestById,
  requests,
  statusMeta,
  userById,
  users,
};
